title: Boni's Page
logo: 
description: Complex is better than complicated
show_downloads: true
google_analytics: G-J0YH541K46
remote_theme: bonioloff/minimal
main_page: https://bonioloff.github.io
linkedin: https://www.linkedin.com/in/bonioloff
hackerrank: https://www.hackerrank.com/bonioloff
github:
  is_user_page: true
  is_project_page: false
